### ISSUE TITLE
Using Bluesky's AppView as handle resolver has privacy implications

### ISSUE THREAD

**Issue by matthieusieben** [mary-ext/atcute#2]
Devs should be aware of the privacy implications of using a particular lib. This is actually why we do not provide a default handle resolver in the official atpropo lib, and require explicit opt-in from the devs using our lib.

**Comment by mary-ext** [comment]
Aware, I think I'd still be providing it as a default (it seems good enough as it is, privacy risks considered), but I'd have to put a lot more disclaimer around it than before.

Now that I've written out a section for additional guides, perhaps there could also be a section on writing your own handle resolution, since all the relevant functions for this are already exposed as a public API.
